<a href="https://colab.research.google.com/github/mooniewexx/DL/blob/main/dl_1_tensor_v1_0_blank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [ ]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [ ]:
x = torch.Tensor(8,8) # аналогично torch.empty
x

tensor([[-4.4687e-08,  4.4836e-41, -4.4687e-08,  4.4836e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  7.7052e+31,  7.2148e+22,  1.5766e-19,
          1.0256e-08,  1.6802e-04,  3.0270e+12],
        [ 4.3358e-08,  1.6599e-07,  1.0721e-08,  1.2400e+16,  2.1707e-18,
          7.0952e+22,  1.7748e+28,  1.8176e+31],
        [ 7.2708e+31,  5.0778e+31,  3.2608e-12,  1.7728e+28,  7.0367e+22,
          2.1715e-18,  6.7701e+22,  5.2004e+22],
        [ 8.1724e+20,  2.1272e+23,  7.9885e+20,  1.0026e-11,  3.3983e+21,
          5.4068e+22,  6.6759e+22,  2.1707e-18],
        [ 7.1450e+31,  6.1970e-04,  2.8909e+26, -1.3672e-40,  4.5919e-41,
          4.1478e-43,  2.7045e-43,  0.0000e+00],
        [-4.4687e-08,  4.4836e-41, -2.4566e-06,  3.1333e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  7.7052e+31,  7.2148e+22,  1.5766e-19,
          1.0256e-08,  1.6802e-04,  3.0270e+12]])

In [ ]:
x = torch.rand(8,8)
print(f'x:\n {x}\n')

x:
 tensor([[0.8857, 0.2268, 0.8703, 0.7993, 0.6696, 0.3490, 0.5270, 0.2500],
        [0.6401, 0.3808, 0.0148, 0.6194, 0.2000, 0.3828, 0.3443, 0.4947],
        [0.0372, 0.2997, 0.4221, 0.0817, 0.5632, 0.5904, 0.6331, 0.2843],
        [0.5133, 0.1126, 0.4910, 0.4508, 0.5489, 0.5558, 0.8640, 0.7320],
        [0.6654, 0.0361, 0.9610, 0.1458, 0.2190, 0.9071, 0.6633, 0.4927],
        [0.4119, 0.7072, 0.6638, 0.5872, 0.5566, 0.4152, 0.4520, 0.7286],
        [0.5815, 0.5503, 0.5089, 0.8461, 0.8278, 0.1716, 0.4469, 0.1662],
        [0.7851, 0.5390, 0.5779, 0.9295, 0.7443, 0.1922, 0.6724, 0.5324]])



In [ ]:
for v in x[1, :]:
  print(v.item())

0.6400920152664185
0.38076794147491455
0.01475536823272705
0.6194478869438171
0.19997507333755493
0.38275986909866333
0.34428316354751587
0.49471408128738403


In [ ]:
# создание тензора из данных:
x1 = torch.Tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.]])

x1

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.]])

In [ ]:
x2 = torch.Tensor(4,8)

x2.fill_(0.) # функции, оканчивающиеся на _ меняют значение тензора слева от точки
x2

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x3 = torch.Tensor([ [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]])

x3

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [4., 3., 2., 6., 5., 2., 3., 4.]])

In [ ]:
# Конкатенация (concatenation):
print('x1', x1, x1.size())
print('x2', x2, x2.size())
# Concatenates 2 tensors on zeroth dimension:
concat1 = torch.cat((x1, x2))
print(concat1, concat1.size())

x1 tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.]]) torch.Size([2, 8])
x2 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]) torch.Size([4, 8])
tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]) torch.Size([6, 8])


In [ ]:
concat2 = torch.cat((concat1, x3), dim=0)
print(concat2, concat2.size())

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]]) torch.Size([8, 8])


1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [ ]:
chet = torch.arange(2, 21, 2)  # Четные числа от 2 до 20
chet

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
nechet = chet + 1          # Ближайшие нечетные числа
nechet

tensor([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [ ]:
products = chet * nechet    # Произведение
products

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
tensor_11x7 = torch.arange(1,102,10).unsqueeze(1) + torch.arange(7)
tensor_11x7

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [ ]:
def create_tensor(n, m):
    texture = torch.tensor([[0, 1], [2, 3]])

    tiled_tensor = texture.repeat(n // 2 + 1, m // 2 + 1)[:n, :m]

    return tiled_tensor



tensor_n_m = create_tensor(4, 5)
tensor_n_m

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [ ]:
t = torch.rand((4, 7)) * 20  # Случайные числа от 0 до 20
print(t)
print(t.min(), t.max())

min_val = t.min()
max_val = t.max()

normalized_t = (t - min_val) / (max_val - min_val)
print(normalized_t)
print(normalized_t.min(), normalized_t.max())

tensor([[14.0442, 13.2594, 17.6470, 15.8602, 15.4265, 14.6127, 16.3380],
        [ 2.8397,  3.2577, 16.1954,  0.4582,  3.9308,  4.9305,  0.0816],
        [ 0.4830,  2.6873, 17.3764,  0.6828, 14.0701, 13.3495,  8.7504],
        [ 4.4116, 14.3889, 14.9887,  2.3915,  3.9455, 14.9715,  6.0485]])
tensor(0.0816) tensor(17.6470)
tensor([[0.7949, 0.7502, 1.0000, 0.8983, 0.8736, 0.8273, 0.9255],
        [0.1570, 0.1808, 0.9174, 0.0214, 0.2191, 0.2761, 0.0000],
        [0.0229, 0.1483, 0.9846, 0.0342, 0.7964, 0.7553, 0.4935],
        [0.2465, 0.8145, 0.8487, 0.1315, 0.2200, 0.8477, 0.3397]])
tensor(0.) tensor(1.)


[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [ ]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))

ar1

tensor([[ 3,  1,  7,  3,  9,  0,  4],
        [ 9,  2,  4,  6,  2,  6,  3],
        [ 9,  1,  0,  3,  5, 10,  3],
        [ 8,  3,  9,  0,  2,  0,  1]])

In [ ]:
ar2

tensor([[ 3,  5,  4,  7,  8,  1,  7],
        [ 4,  6, 10,  0,  2,  4,  4],
        [ 2,  8,  6,  3,  9,  2,  3],
        [ 1,  9,  7, 10,  3,  6,  9]])

In [ ]:
max_tensor = torch.max(ar1, ar2)
max_tensor

tensor([[ 3,  5,  7,  7,  9,  1,  7],
        [ 9,  6, 10,  6,  2,  6,  4],
        [ 9,  8,  6,  3,  9, 10,  3],
        [ 8,  9,  9, 10,  3,  6,  9]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [ ]:
t_7 = torch.randint(0, 101, (20,))

t_7

tensor([82, 35,  6, 64, 77, 52, 68, 13,  6, 52, 42, 55,  3, 42, 42, 35, 34, 17,
        76,  8])

In [ ]:
torch.sort(t_7).values

tensor([ 3,  6,  6,  8, 13, 17, 34, 35, 35, 42, 42, 42, 52, 52, 55, 64, 68, 76,
        77, 82])

In [ ]:
v2 = torch.sort(t_7).values[-2]
v2

tensor(77)

In [ ]:
idx = (t_7 == v2).nonzero(as_tuple=True)[0].item()

idx

4

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [ ]:
base = torch.arange(1, 8)  # [1, 2, 3, ..., 7]
steps = torch.arange(0, 110, 10).unsqueeze(1)  # [[0], [10], [20], ..., [100]]

tensor_11x7 = base + steps
tensor_11x7

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [ ]:
a_2d = torch.tensor([[3, 3, 3], [4, 4, 4], [5, 5, 5]])
b_1d = torch.tensor([1, 2, 3])

b_1d.unsqueeze(1) # yвеличиваем размерность b_1d для совместимости

tensor([[1],
        [2],
        [3]])

In [ ]:
result = a_2d - b_1d.unsqueeze(1)
result

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [ ]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

In [ ]:
torch.where(a == b)[0]

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [ ]:
t = torch.arange(9).view(3,3)
t

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
torch.flip(t, dims=[0, 1]) # dims=[0, 1] - переворачиваем и по строкам и по столбцам

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [ ]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [ ]:
import numpy as np

In [ ]:
t = np.arange(9).reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
t[:, [1, 2]] = t[:, [2, 1]]
t

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
t = torch.randint(0, 11, (8,10))
t

tensor([[ 8,  3,  9, 10,  3,  8,  0,  2,  3,  7],
        [ 2,  4,  9, 10, 10,  0, 10,  0,  2,  9],
        [10, 10, 10,  9,  8,  1,  4,  9,  5,  9],
        [ 8,  5,  0,  4,  4,  1,  5,  9,  2,  4],
        [ 3, 10,  2,  1,  3,  1,  8,  2,  7,  2],
        [ 5,  2,  8,  0,  7,  1,  9,  2,  9,  2],
        [10, 10,  2,  1,  8,  5,  3,  8,  2,  6],
        [10,  5,  8,  4,  7,  7,  4,  6,  1, 10]])

In [ ]:
t.sum(dim=1)

tensor([53, 56, 75, 42, 39, 45, 55, 62])

In [ ]:
min_sum_i= torch.argmin(t.sum(dim=1))

print(t[min_sum_i])
print("Индекс:", min_sum_i.item())

tensor([ 3, 10,  2,  1,  3,  1,  8,  2,  7,  2])
Индекс: 4


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
t = torch.randint(0, 101, (20,))
print(t)

t_ = torch.cat((t[t < 30], t[t > 70]))

t_

tensor([32,  5, 22, 29, 96, 23, 43, 97, 50, 38,  9, 13, 95, 10, 10, 46, 44, 43,
         0, 51])


tensor([ 5, 22, 29, 23,  9, 13, 10, 10,  0, 96, 97, 95])

In [ ]:
t = torch.randint(0, 101, (20,))
print(t)

torch.clamp(t, min=30, max=70)

tensor([ 32,  96,   3,   2, 100,  36,  94,   2,  37,  69,  78,  40,  67,  20,
         85,  89,  64,  63,   4,  16])


tensor([32, 70, 30, 30, 70, 36, 70, 30, 37, 69, 70, 40, 67, 30, 70, 70, 64, 63,
        30, 30])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [ ]:
tensor1 = torch.randint(0, 11, (30, 3))
tensor2 = torch.randint(0, 11, (30, 3))

vals = tensor1[tensor1 > tensor2]

sum_v = vals.sum()

print(tensor1)
print(tensor2)
print(vals)
print(sum_v.item())

tensor([[ 3, 10, 10],
        [10,  2,  8],
        [ 3,  5,  4],
        [ 9,  8,  4],
        [ 8,  3,  4],
        [ 0,  2,  1],
        [ 3, 10,  8],
        [ 4,  4,  6],
        [ 7,  3,  0],
        [ 0,  6,  3],
        [ 9,  8,  1],
        [ 8,  0,  1],
        [ 3,  4,  4],
        [10,  3,  5],
        [ 0,  4,  9],
        [ 3, 10,  2],
        [ 2, 10,  6],
        [ 3,  2,  8],
        [ 5, 10,  1],
        [10,  9,  4],
        [ 0,  2,  4],
        [ 1,  5, 10],
        [ 6,  6,  1],
        [ 0,  6,  0],
        [ 0,  9,  5],
        [ 1,  6,  1],
        [10,  9,  8],
        [ 4,  1,  5],
        [ 7,  8,  4],
        [ 0,  1,  0]])
tensor([[ 3,  6,  9],
        [ 0,  3,  7],
        [ 9, 10,  0],
        [ 9,  8,  7],
        [ 0,  6,  0],
        [10,  5,  1],
        [ 5,  1,  4],
        [ 5,  5,  4],
        [10,  4,  1],
        [ 1,  1,  9],
        [ 6, 10,  1],
        [ 2,  5,  0],
        [ 9,  2,  1],
        [ 9,  4,  1],
        [ 4,  4,  9],
        [

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [ ]:
tensor = torch.randint(0, 11, (20, 20))

above_main_diag = tensor[:-1, 1:].diagonal()

print(tensor)

tensor([[ 6,  6,  4,  2,  9,  1,  5,  9,  4,  9,  0, 10,  7,  6,  4,  3,  9,  2,
          3,  1],
        [ 9,  8,  9, 10,  9,  3,  9, 10,  4,  7,  9, 10,  5,  0,  4,  5,  1,  8,
          5,  4],
        [ 5,  2,  6,  4,  8,  0, 10,  0,  6,  1,  0,  8,  0,  2,  3,  0, 10,  7,
          8, 10],
        [ 3,  1,  9,  2,  5,  7,  0, 10,  8,  8, 10,  5,  0,  5,  4,  3,  5,  6,
          4,  4],
        [10,  9,  4,  6,  2,  3,  8,  2, 10,  9,  7,  8,  7,  2,  3,  2,  7,  2,
         10,  6],
        [ 6,  9,  7,  8,  9, 10,  7,  4,  5,  9,  8,  0,  9,  9,  3,  9,  6,  2,
          3,  5],
        [ 8,  7,  9,  3,  8,  4,  3,  4,  2,  2,  8,  6,  0, 10,  2,  6,  8,  0,
         10,  9],
        [ 9,  7,  9,  1,  1,  8,  9,  7,  5,  3,  4,  6,  1,  7,  5,  9, 10, 10,
          6,  9],
        [ 0,  0, 10,  0,  0,  5,  1,  5,  1,  1,  7,  4,  7,  9,  6,  5,  6,  9,
          5,  2],
        [ 0,  4,  5,  6,  9,  1,  4,  0,  4,  8,  1,  6,  8,  8,  5,  4,  8, 10,
          1,  1],
        [ 

In [ ]:
print("Элементы над главной диагональю:", above_main_diag)

Элементы над главной диагональю: tensor([6, 9, 4, 5, 3, 7, 4, 5, 1, 1, 4, 7, 6, 3, 0, 2, 8, 8, 5])


1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [ ]:
ar1 = torch.randint(0, 11, (5, 10))
ar2 = torch.randint(0, 11, (5, 10))
print(ar1)
print(ar2)

ar1[ar1 == ar2] *= 2

print('После:', ar1)

tensor([[ 0,  2,  7, 10,  7,  9,  9,  2,  9,  5],
        [ 7, 10,  4,  1,  2,  6,  6,  2,  6,  6],
        [10,  2,  7,  3,  0,  9,  4, 10,  9, 10],
        [ 3,  8,  6,  8,  2,  7,  8,  0,  3,  7],
        [ 8,  1,  0, 10,  8,  6,  1,  8,  9,  4]])
tensor([[ 0,  4,  1,  1,  8,  3, 10,  4,  3,  9],
        [10,  6,  6,  6,  1,  0,  5,  0,  2,  5],
        [ 1,  1, 10,  9, 10,  4,  5,  2,  2,  5],
        [ 4,  8,  4,  9,  6, 10,  3,  0,  5,  4],
        [ 7,  8,  2,  3,  4,  5,  3,  1,  4,  3]])
После: tensor([[ 0,  2,  7, 10,  7,  9,  9,  2,  9,  5],
        [ 7, 10,  4,  1,  2,  6,  6,  2,  6,  6],
        [10,  2,  7,  3,  0,  9,  4, 10,  9, 10],
        [ 3, 16,  6,  8,  2,  7,  8,  0,  3,  7],
        [ 8,  1,  0, 10,  8,  6,  1,  8,  9,  4]])


1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [ ]:
ar1 = torch.randint(0, 11, (4,7))
ar2 = torch.randint(0, 11, (4,7))
ar3 = torch.randint(0, 11, (4,7))

print(ar1)
print(ar2)
print(ar3)
ar1[(ar1 > ar2) & (ar1 < ar3)]

tensor([[ 8, 10,  2,  7,  1,  1,  8],
        [ 3,  4,  4,  6,  7,  2,  1],
        [ 0,  9,  7,  0,  4,  8,  7],
        [ 3, 10,  4,  0,  3,  0,  4]])
tensor([[ 8, 10,  4,  8, 10,  5,  9],
        [ 0,  5,  5,  8, 10, 10,  2],
        [ 6,  1,  4,  7,  8,  7,  3],
        [ 2, 10,  4,  5,  7,  4,  2]])
tensor([[ 5,  4,  5,  4,  5,  2, 10],
        [ 8, 10,  3, 10,  8,  8,  1],
        [ 8,  4,  5,  5,  9,  7,  8],
        [ 6,  4,  6,  5,  6,  0,  7]])


tensor([3, 7, 3, 4])

In [ ]:
ar1[(ar1 > ar2) & (ar1 < ar3)] = 0

In [ ]:
ar1

tensor([[ 8, 10,  2,  7,  1,  1,  8],
        [ 0,  4,  4,  6,  7,  2,  1],
        [ 0,  9,  7,  0,  4,  8,  0],
        [ 0, 10,  4,  0,  3,  0,  0]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [ ]:
ar1 = torch.randint(0, 20, (20,5))
maxis = ar1.max(dim=1, keepdim=True).values # сохраняет размерность
count = (ar1 == maxis).sum(dim=0) # сколько раз встречается max по столбцам
print(maxis)
(count >= 5).nonzero()

tensor([[19],
        [14],
        [13],
        [18],
        [18],
        [ 9],
        [18],
        [13],
        [15],
        [19],
        [17],
        [18],
        [17],
        [13],
        [13],
        [16],
        [19],
        [12],
        [19],
        [ 8]])


tensor([[0],
        [1],
        [3],
        [4]])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [ ]:
ar1 = torch.rand((4, 7))
ar1

tensor([[0.7567, 0.1794, 0.3431, 0.9887, 0.5090, 0.0771, 0.1986],
        [0.5280, 0.3472, 0.5319, 0.7105, 0.3682, 0.7619, 0.4247],
        [0.6596, 0.2847, 0.9935, 0.1962, 0.7314, 0.2263, 0.1878],
        [0.4283, 0.7110, 0.9252, 0.6796, 0.5196, 0.7273, 0.7260]])

In [ ]:
index = torch.argmax(ar1)
row, col = divmod(index.item(), 7) # в индекс строки и столбца
ar1[row+1:, :] = 0 # строки ниже
ar1[row, col+1:] = 0 # элементы правее
ar1

tensor([[0.7567, 0.1794, 0.3431, 0.9887, 0.5090, 0.0771, 0.1986],
        [0.5280, 0.3472, 0.5319, 0.7105, 0.3682, 0.7619, 0.4247],
        [0.6596, 0.2847, 0.9935, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [ ]:
tt = torch.tensor([2, 3, 2, 2, 2, 1])

cols = tt.max().item()
encoded = torch.nn.functional.one_hot(tt, num_classes = cols+1)
encoded

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре.
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [ ]:
arr = torch.randint(100, (1,20))
arr

tensor([[90, 10, 79, 88, 13, 22, 93, 48, 72, 59, 23, 48, 18, 24, 51, 19,  5,  9,
         43, 30]])

In [ ]:
unique, counts = torch.unique(arr, return_counts = True)
pop = unique[torch.argmax(counts)].item()
pop, max(counts).item()

(48, 2)

In [ ]:
(arr == pop).nonzero() # индексы в тензоре, соответствующие самому частому значению

tensor([[ 0,  7],
        [ 0, 11]])

In [ ]:
# при двух значениях, имеющих наибольшую встречаемость

pops = unique[counts == max(counts)]
pops

tensor([48])

In [ ]:
ind = [(arr == i).nonzero() for i in pops]; ind

[tensor([[ 0,  7],
         [ 0, 11]])]

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [ ]:
x = torch.linspace(0, 10, 1000)
y = x * torch.sin(x)

mask = y > 0.5

fraction = torch.sum(mask) / len(x)
fraction.item()

0.5230000019073486

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [ ]:
n = 100
sieve = np.ones(n + 1, dtype=bool)
sieve[0:2] = False  # 0 и 1 не простые
for i in range(2, int(n**0.5) + 1):
    sieve[i*i:n+1:i] = False

primes = np.nonzero(sieve)[0]
primes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

distance = torch.sqrt(torch.sum((a - b) ** 2))
distance.item()

5.196152210235596

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100.
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [ ]:
tensor = torch.randint(0, 101, (20, 3), dtype=torch.float32)
lengths = torch.sqrt(torch.sum(tensor**2, axis=1))

sorted_tensor = tensor[lengths.argsort()]
print(sorted_tensor)

tensor([[ 3., 35., 35.],
        [25.,  7., 59.],
        [35., 27., 50.],
        [55., 29., 41.],
        [60., 51.,  0.],
        [65., 45.,  7.],
        [56., 62., 18.],
        [ 2., 30., 81.],
        [97.,  8., 11.],
        [72., 68., 19.],
        [82.,  2., 67.],
        [80., 47., 57.],
        [46., 80., 69.],
        [82., 25., 83.],
        [79., 48., 86.],
        [89., 68., 62.],
        [86., 53., 88.],
        [85., 86., 86.],
        [98., 95., 59.],
        [98., 71., 92.]])


1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [ ]:
x = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])

local_maxima = (x[1:-1] > x[:-2]) & (x[1:-1] > x[2:])
indices = torch.nonzero(local_maxima) + 1  # смещаем индексы

indices.flatten().tolist()

[2, 5]

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
arr = np.random.rand(100)
target = 0.5

closest_value = arr[np.abs(arr - target).argmin()]
closest_value

0.5031416936480787

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = torch.tensor([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]], dtype=torch.float32)
B = torch.tensor([[3, -1], [2, 1]], dtype=torch.float32)
C = torch.tensor([[7, 21], [11, 8], [8, 4]], dtype=torch.float32)

A_inv = torch.inverse(A)
B_inv = torch.inverse(B)

X = A_inv @ (-C) @ B_inv
X

tensor([[ 1.0000e+00, -1.1921e-07],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [ ]:
a1 = torch.tensor([3, -3, 0, 7], dtype=torch.float32)
a2 = torch.tensor([2, 2, 4, 7], dtype=torch.float32)
a3 = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
a4 = torch.tensor([5, -4, 1, 3], dtype=torch.float32)

matrix = torch.stack([a1, a2, a3, a4], dim=1)

rank = torch.linalg.matrix_rank(matrix)

print(f"Ранг: {rank}")

Ранг: 3


Векторы линейно зависимы, т.к. ранг < 4

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами.

In [ ]:
mu, sigma = 0, 10
data = torch.normal(mu, sigma, (200,))

hist, bins = torch.histogram(data, bins=20)
hist

Гистограмма:
 tensor([ 3.,  2.,  5.,  4., 13.,  9., 18., 13., 23., 25., 15., 13., 15., 13.,
        10.,  8.,  3.,  3.,  4.,  1.])
